apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: hwmachineproviderspecs.helloworld.k8s.io
spec:
  group: helloworld.k8s.io
  names:
    kind: HWMachineProviderSpec
    plural: hwmachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            imageURI:
              description: Image URL to be provisioned
              type: string
            memoryInGB:
              description: Amount of RAM in GBs
              format: int64
              type: integer
            name:
              description: Name of the machine
              type: string
            userDataURI:
              description: UserData URI of cloud-init image
              type: string
            vcpu:
              description: Number of virtual CPU
              format: int64
              type: integer
          required:
          - name
          - vcpu
          - memoryInGB
          - imageURI
          - userDataURI
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
